#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     IROne,          sensorI2CCustom)
#pragma config(Motor,  mtr_S1_C1_1,     motorD,        tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorF,        tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    servo2,               tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
int left;
int right;

void harvesterMotors()
{
	if(abs(joystick.joy2_y2) > 10)
	{
		motor[motorG] = joystick.joy2_y2;
	}
	else
	{
		motor[motorG] = 0;
	}
}

void liftMotors()
{
	int liftFullSpeed = 50;
	int liftHalfSpeed = 25;
	if(joystick.joy2_Buttons == pow(2, 1))
	{
		motor[motorF] = liftFullSpeed;
		wait1Msec(1);
	}
	else if(joystick.joy2_Buttons == pow(2, 0))
	{
		motor[motorF] = -liftFullSpeed;
		wait1Msec(1);
	}
	else if(joystick.joy2_Buttons == pow(2, 2))
	{
		motor[motorF] = -liftHalfSpeed;
		wait1Msec(1);
	}
	else if(joystick.joy2_Buttons == pow(2, 3))
	{
		motor[motorF] = liftHalfSpeed;
		wait1Msec(1);
	}
	else
	{
		motor[motorF] = 0;
		wait1Msec(1);
	}
}

void driveMotors()
{
	if(joystick.joy1_Buttons == pow(2, 5))
	{
		left = joystick.joy1_y1;
		right = joystick.joy1_y2;
	}
	else
	{
		left = joystick.joy1_y1 / 2;
		right = joystick.joy1_y2 / 2;
	}
	if(joystick.joy1_Buttons == pow(2, 7))
	{
		left = -left;
		right = -right;
	}
	else
	{
		left = left;
		right = right;
	}
	if(joystick.joy2_Buttons == pow(2, 7))
	{
		left = -left;
		right = -right;
	}
	else
	{
		left = left;
		right = right;
	}

	if(abs(joystick.joy1_y1) > 10)
	{
		motor[motorE] = left;
	}
	else
	{
		motor[motorE] = 0;
	}

	if(abs(joystick.joy1_y2) > 10)
	{
		motor[motorD] = right;
	}
	else
	{
		motor[motorD] = 0;
	}
}

task main()
{
	waitForStart();
	while(true)
	{
		getJoystickSettings(joystick);
		driveMotors();
		harvesterMotors();
		liftMotors();
	}
}
